# File: .github/workflows/repo-sync.yml
name: sync-hectorqin-reader
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-hectorqin-reader
