# File: .github/workflows/repo-sync.yml
name: sync-hectorqin-reader
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-hectorqin-reader
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync hectorqin-reader
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://gitee.com/lxk0301/scripts"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
